### ISSUE TITLE
Modelo relacional de la base de datos de la app

### ISSUE THREAD

**Issue by Aisaac123** [Aisaac123/cartera-app#1]
Realizar una primera version del modelo relacional de la aplicacion con los requisitos del archivo [README.md](https://github.com/Aisaac123/Cartera/blob/main/README.md)

**Comment by C4lumny** [comment]
# Modelo Relacional (MR) de Cartera 💿 
![Cartera-E-R](https://github.com/Aisaac123/Cartera/assets/105754395/14adf7f9-5916-4f2b-bb2e-736bec35ed74)

Tomando en cuenta los requerimientos funcionales y no funcionales, realicé el diagrama que adjunté previamente. En aras de la construcción de este, pensé en algunos ajustes y 7 o recomendaciones (En vista de que tienes más experiencia que yo en esto). Puntos a tener en cuenta:

- La tabla de estadísticas e informes la dejé en blanco puesto que no tengo experiencia en este rubro, y no se como se trabajan en la base de datos

- No sé que tan bien esté, pero considero y mantengo la opinión de crear una tabla tarjetas, que cuente con la información de las tarjetas y ésta se encuentre referenciada en la tabla de cartera, con una relación de 1 cartera - varias tarjetas

> Diagrama realizado en dia - Te lo mando por whatsapp

**Comment by Aisaac123** [comment]
- No se necesita una tabla de estadisticas.
- Una cartera puede tener varias tarjetas y una tarjeta solo pertenece a una cartera.
- Las tarjetas deben ser otra tabla distinta.
- Añadir columna tipo text nullable a las tarjetas llamada "Proposito".
- Añadir columna "Ingreso" de tipo bool default true.
- Añadir columna "Egreso" de tipo bool default true.
- Las tarjetas tienen un banco asociado, un banco puede tener varias tarjetas.
- La columna tipo debe ser una tabla aparte de 1 a n con la transaccion, cambiar nombre de tipo a "tipo_transaccion"
- La columna categoria debe ser una tabla de 1 a n con la transaccion, cambari el nombre a "categoria_transaccion", esta foranea puede ser null
- Se necesita una nueva tabla llamada Destinos, que me indique a donde y cuando llega el dinero relacionada con la tabla transaccion, esta foranea puede ser null en la tabla transaccion. Destinos tambien puede estar relacionado a una tarjeta, esta relacion tambien puede ser null

### Importante 

El modelo no cumple del todo con el requerimiento de automtizacion en las transacciones, se necesita poder programar transacciones en ciertas fechas y poder modificar un estado de la transaccion para saber si estan atrasadas, adelantadas conforme a la fecha estipulada

**Comment by C4lumny** [comment]
# Corrección Modelo Relacional base de datos
![Cartera-MR](https://github.com/Aisaac123/Cartera/assets/105754395/51dd3417-4eb3-451c-9abb-97a99a40e2ab)
